const toXY   = ({x, y}) => ({x, y});
const coords = ({x, y}) => [x, y];
const pIsNaN = ({x, y}) => isNaN(x) || isNaN(y);
const eql    = (a, b) => a.x === b.x && a.y === b.y;
const dist   = (a, b) => Math.sqrt((a.x - b.x) ** 2 + (a.y - b.y) ** 2);
const add    = (a, b) => ({x: a.x + b.x, y: a.y + b.y});
const sub    = (a, b) => ({x: a.x - b.x, y: a.y - b.y});
const mul    = (a, b) => ({x: a.x * b.x, y: a.y * b.y});
const dot    = (a, b) => a.x * b.x + a.y * b.y;
const scale  = (v, s) => ({x: v.x * s, y: v.y * s});
const length = v => dist(v, {x: 0, y: 0});
const norm   = v => scale(v, 1 / length(v));
